### PR TITLE
Only send email to one time donors

### PR DESCRIPTION
**Pull request by iox**

### CODE REVIEW

**Comment by rasmusagdestein** [comment]
Hi Ignacio.

Just looked at this.
If a user creates a recurring donation they will get the first email right ?

Warm regards,
Rasmus

**Comment by iox** [comment]
Actually they won't receive it, you are right. They would only get a Paypal notification.

I'm going to fix it, good catch, thanks.

**Comment by iox** [comment]
Hi Rasmus,

I have updated the code to make it clearer, log more information and make sure that recurring donors get a thank you email with the first payment.

Warm regards,
Ignacio

**Comment by rasmusagdestein** [comment]
Hi Ignacio,
I have merged the updates and will upload them when I get back home. 

Warm regards
Rasmus

**Comment by iox** [comment]
Great thanks!

**Comment by rasmusagdestein** [comment]
Hi Ignacio.

Plugin is now updated to the latest version.

Warm regards,
Rasmus

**Pull request merged**
