### PR TITLE
Send notification email if a donation is below the subscriber minimum am...

### PR DESCRIPTION
**Pull request by iox**
...ount

### CODE REVIEW

**Comment by rasmusagdestein** [comment]
Hi Ignacio.

Just looked at the changes.

As I see it this will only check a users donations if the user is still donating ?  Or am I wrong ?

I think we need somehow to test all the users (which are donating through paypal) using a WP Cron job or something maybe once a week. 
What do you think ?

Warm regards 
Rasmus
  Sent from my IQTELL Virtual Workspace

**Comment by iox** [comment]
Hi Rasmus,

You are right, these changes are only for donations of less than 100 DKK. We still need:
- A cron job to check for cancelled subscriptions and send notification emails (we can search in the DB for recurring donors who have not donated in the last 45 days).
- A cron job to check for incomplete subscriptions and send notification emails (went to Paypal but never confirmed it).

I'll work on those next week :).

Warm regards,
Ignacio

**Comment by rasmusagdestein** [comment]
Hi Ignacio,

Sorry I think we have a little misunderstanding.

The rule is that a supporter needs to donate minimum 100 DKK per year, not per month. 
So actually it doesn't make much sense to check each donation, when it's made. 

I think a cron job should check how much a supporter has donated the last year - if that's under 100 DKK we should receive a notification.

We should also be able to use the respond from paypal when someone cancel or fails to donate. 
 
A cron job to check for incomplete subscriptions and send notification emails (went to Paypal but never confirmed it).
We also need to get notified if the user didn't get to paypal at all (clicked but our site failed to send them to paypal)

Warm regards
Rasmus
  Sent from my IQTELL Virtual Workspace

**Comment by iox** [comment]
Hi Rasmus,

Nothing to be sorry about, I should have asked for more information! I'll close this pull request and delete this branch. The good part is that it's not a waste of time, now I have an even better understanding of Seamless Donations :).

To make sure that I'm on the right track, I have updated the list of requirements in the Evernote notebook called "About Seamless Donations plugin". If you have a moment, please take a look at it and check if everything is clear. The items in "italic" are already completed, and I'm going to work in the rest of items in order.

Warm regards,
Ignacio

**Comment by rasmusagdestein** [comment]
Hi Ignacio,

I have reviewed the list og requirements and it seems fine.
I added one thing (colored) - It's about if a user tries to donate but is never send to paypal. 

Warm regards,
Rasmus
  Sent from my IQTELL Virtual Workspace

**Comment by iox** [comment]
Perfect Rasmus, I have seen your addition. I'll work on these.

**Pull request closed without merging**
